### ISSUE TITLE
How to provide Peppol access for my users

### ISSUE THREAD

**Issue by lsaffre** [iterasdev/peppol-py#2]
Thank you for publishing your work here!

I am the developer of a FOSS accounting software and I have 8 clients in Belgium who use my software to write sales invoices. Until now we didn't care about e-invoicing because we are small. But now we are forced to address the topic because in 2026 all Belgian companies will need to send invoices via Peppol. So I started to investigate the topic in order to add this feature to my software. Meanwhile my software is already able to produce an XML file in UBL syntax (I used the [Ecosio validator](https://ecosio.com/en/peppol-and-xml-document-validator/) to verify that the XML files are valid.

But now we are stuck: how should my software upload these XML files into the Peppol network? At this point I found peppol-py, which seems to match our needs quite closely. But I am probably still missing something. When I call it with myself as receiver, like this:

  sender.py -- receiver 9931:EE100588749 --document sample-invoice.xml --test

then I get as response: socket.gaierror: [Errno -2] Name or service not known

Do I need to become an Access Point in order to use this script? After reading the guide about [How to set up a Peppol AP](https://peppol.org/wp-content/uploads/2024/03/how_to_set-up_a__post-award__peppol_access_point_v2.0.pdf)  i guess that becoming myself an AP is beyond my capacities. Also my customers can use a national platform, Hermes, for receiving their invoices and printing converting them into pdf documents, so I don't need to implement a full Access Point.

Du you have any ideas or hints for me?

**Comment by arj03** [comment]
@lsaffre yes, you need to become a part of the network and have keys to do anything. It's a closed network. There is also a test you have to take in order to be certified. I used peppol-py for that also.

**Comment by lsaffre** [comment]
Thanks, yes, now I saw that Iteras ApS is a [certified AP](https://peppol.org/members/peppol-certified-service-providers/). And as a one-person company I am pretty sure that I have no chance to become such an AP: even if I would manage the technical part, the administrative part of this certification process is simply impossible for an individual. (Please let me know if you disagree!)

**Comment by arj03** [comment]
There is a substantial fee to use the network. Prices are here: https://peppol.org/join/fees/. The certification process does take some time, so might be a too much. It is a pity they ended up with this, it could have been really simple protocol.

**Comment by lsaffre** [comment]
Yes, it is truly a pity. Becoming an AP is out of reach for me, so my customers must find a service provider who acts as their AP. Peppol (as it is implemented) probably means that I will stop developing [accounting functionality in Lino](https://using.lino-framework.org/plugins/accounting.html).
